#!/bin/bash
# RHEL 8 / Rocky 8 / AlmaLinux 8 时间同步配置（chrony）
# 用法：
#   sudo bash rhel8-setup-chrony.sh
#   sudo bash rhel8-setup-chrony.sh --timezone Asia/Shanghai
#   sudo bash rhel8-setup-chrony.sh --servers "ntp.aliyun.com ntp.tencent.com"
#   sudo bash rhel8-setup-chrony.sh --timezone Asia/Shanghai --servers "ntp.aliyun.com"

set -euo pipefail

TIMEZONE="Asia/Shanghai"
NTP_SERVERS=("ntp.aliyun.com" "ntp.tencent.com" "time.windows.com")
CHRONY_CONF="/etc/chrony.conf"
BACKUP_SUFFIX="$(date +%Y%m%d%H%M%S)"

usage() {
  cat <<'EOF'
用法: sudo bash rhel8-setup-chrony.sh [选项]

选项:
  --timezone <区域>     时区，默认 Asia/Shanghai
  --servers "<主机...>"  NTP 服务器列表（空格分隔）
  -h, --help            显示帮助

示例:
  sudo bash rhel8-setup-chrony.sh
  sudo bash rhel8-setup-chrony.sh --timezone Asia/Shanghai
  sudo bash rhel8-setup-chrony.sh --servers "ntp.aliyun.com ntp.ntsc.ac.cn"
EOF
}

log() { printf '[INFO] %s\n' "$*"; }
warn() { printf '[WARN] %s\n' "$*" >&2; }
die() { printf '[ERROR] %s\n' "$*" >&2; exit 1; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    die "请使用 root 或 sudo 运行此脚本"
  fi
}

detect_os() {
  if [[ ! -f /etc/os-release ]]; then
    die "无法识别操作系统（缺少 /etc/os-release）"
  fi
  # shellcheck disable=SC1091
  . /etc/os-release
  case "${ID:-}:${VERSION_ID:-}" in
    rhel:8*|rocky:8*|almalinux:8*|centos:8*|ol:8*)
      log "检测到系统: ${PRETTY_NAME:-$ID $VERSION_ID}"
      ;;
    *)
      warn "当前系统为 ${PRETTY_NAME:-unknown}，脚本按 RHEL 8 / chrony 方式配置，请自行确认兼容性"
      ;;
  esac
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --timezone)
        [[ $# -ge 2 ]] || die "--timezone 需要参数"
        TIMEZONE="$2"
        shift 2
        ;;
      --servers)
        [[ $# -ge 2 ]] || die "--servers 需要参数"
        # shellcheck disable=SC2206
        NTP_SERVERS=($2)
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "未知参数: $1（使用 --help 查看用法）"
        ;;
    esac
  done
  [[ ${#NTP_SERVERS[@]} -gt 0 ]] || die "至少需要一个 NTP 服务器"
}

install_chrony() {
  if command -v chronyd >/dev/null 2>&1; then
    log "chrony 已安装"
  else
    log "安装 chrony..."
    if command -v dnf >/dev/null 2>&1; then
      dnf install -y chrony
    elif command -v yum >/dev/null 2>&1; then
      yum install -y chrony
    else
      die "未找到 dnf/yum，无法安装 chrony"
    fi
  fi
}

backup_conf() {
  if [[ -f "${CHRONY_CONF}" ]]; then
    cp -a "${CHRONY_CONF}" "${CHRONY_CONF}.bak.${BACKUP_SUFFIX}"
    log "已备份配置: ${CHRONY_CONF}.bak.${BACKUP_SUFFIX}"
  fi
}

configure_chrony() {
  log "写入 chrony 配置: ${CHRONY_CONF}"
  backup_conf

  local server_lines=""
  local s
  for s in "${NTP_SERVERS[@]}"; do
    server_lines+="server ${s} iburst"$'\n'
  done

  cat > "${CHRONY_CONF}" <<EOF
# Generated by rhel8-setup-chrony.sh on $(date -Iseconds)
# NTP servers
${server_lines}
# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
rtcsync

# Specify directory for log files.
logdir /var/log/chrony
EOF
}

set_timezone_and_ntp() {
  if ! timedatectl list-timezones | grep -Fxq "${TIMEZONE}"; then
    die "无效时区: ${TIMEZONE}"
  fi
  log "设置时区为 ${TIMEZONE}"
  timedatectl set-timezone "${TIMEZONE}"

  log "启用 NTP 同步"
  timedatectl set-ntp true
}

enable_service() {
  log "启用并启动 chronyd"
  systemctl enable --now chronyd
  systemctl restart chronyd
}

show_status() {
  echo
  log "==== timedatectl 状态 ===="
  timedatectl status || true
  echo
  log "==== chronyc tracking ===="
  chronyc tracking || true
  echo
  log "==== chronyc sources -v ===="
  chronyc sources -v || true
  echo
  log "配置完成。若 sources 暂无 *（当前同步源），请等待数秒后再执行: chronyc sources -v"
}

main() {
  parse_args "$@"
  require_root
  detect_os
  install_chrony
  configure_chrony
  set_timezone_and_ntp
  enable_service
  show_status
}

main "$@"
