#!/bin/bash
# RHEL 8 / Rocky 8 / AlmaLinux 8 时间同步配置（chrony）
#
# 有外网（默认公网 NTP）：
#   sudo bash rhel8-setup-chrony.sh
#
# 无外网（必须指定内网 NTP）：
#   sudo bash rhel8-setup-chrony.sh --offline --servers "10.0.0.10 10.0.0.11"
#
# 无外网且本机作为内网 NTP 服务端（可再同步上游，或仅本地时钟）：
#   sudo bash rhel8-setup-chrony.sh --as-server --allow "10.0.0.0/24" --servers "10.0.0.1"
#   sudo bash rhel8-setup-chrony.sh --as-server --allow "10.0.0.0/24" --local-stratum 10

set -euo pipefail

TIMEZONE="Asia/Shanghai"
NTP_SERVERS=("ntp.aliyun.com" "ntp.tencent.com" "time.windows.com")
SERVERS_SET=0
OFFLINE=0
AS_SERVER=0
ALLOW_NETS=()
LOCAL_STRATUM=""
CHRONY_CONF="/etc/chrony.conf"
BACKUP_SUFFIX="$(date +%Y%m%d%H%M%S)"

usage() {
  cat <<'EOF'
用法: sudo bash rhel8-setup-chrony.sh [选项]

选项:
  --timezone <区域>       时区，默认 Asia/Shanghai
  --servers "<主机...>"    NTP 服务器列表（空格分隔）
  --offline               无外网模式：禁止使用默认公网 NTP，必须配合 --servers
  --as-server             将本机配置为内网 NTP 服务端
  --allow "<网段...>"      允许哪些网段访问本机 NTP（可多个，空格分隔；配合 --as-server）
  --local-stratum <N>     无上游可用时使用本地时钟（常见 8~12；配合 --as-server）
  -h, --help              显示帮助

示例:
  # 有外网
  sudo bash rhel8-setup-chrony.sh

  # 无外网：同步到内网 NTP
  sudo bash rhel8-setup-chrony.sh --offline --servers "ntp.corp.local 10.0.0.10"

  # 无外网：本机作为内网 NTP（有上游）
  sudo bash rhel8-setup-chrony.sh --as-server --allow "10.0.0.0/8" --servers "10.1.1.1"

  # 无外网：本机作为内网 NTP（无上游，本地时钟）
  sudo bash rhel8-setup-chrony.sh --as-server --allow "10.0.0.0/8" --local-stratum 10
EOF
}

log() { printf '[INFO] %s\n' "$*"; }
warn() { printf '[WARN] %s\n' "$*" >&2; }
die() { printf '[ERROR] %s\n' "$*" >&2; exit 1; }

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    die "请使用 root 或 sudo 运行此脚本"
  fi
}

detect_os() {
  if [[ ! -f /etc/os-release ]]; then
    die "无法识别操作系统（缺少 /etc/os-release）"
  fi
  # shellcheck disable=SC1091
  . /etc/os-release
  case "${ID:-}:${VERSION_ID:-}" in
    rhel:8*|rocky:8*|almalinux:8*|centos:8*|ol:8*)
      log "检测到系统: ${PRETTY_NAME:-$ID $VERSION_ID}"
      ;;
    *)
      warn "当前系统为 ${PRETTY_NAME:-unknown}，脚本按 RHEL 8 / chrony 方式配置，请自行确认兼容性"
      ;;
  esac
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --timezone)
        [[ $# -ge 2 ]] || die "--timezone 需要参数"
        TIMEZONE="$2"
        shift 2
        ;;
      --servers)
        [[ $# -ge 2 ]] || die "--servers 需要参数"
        # shellcheck disable=SC2206
        NTP_SERVERS=($2)
        SERVERS_SET=1
        shift 2
        ;;
      --offline)
        OFFLINE=1
        shift
        ;;
      --as-server)
        AS_SERVER=1
        shift
        ;;
      --allow)
        [[ $# -ge 2 ]] || die "--allow 需要参数"
        # shellcheck disable=SC2206
        ALLOW_NETS=($2)
        shift 2
        ;;
      --local-stratum)
        [[ $# -ge 2 ]] || die "--local-stratum 需要参数"
        LOCAL_STRATUM="$2"
        [[ "${LOCAL_STRATUM}" =~ ^[0-9]+$ ]] || die "--local-stratum 必须是数字"
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        die "未知参数: $1（使用 --help 查看用法）"
        ;;
    esac
  done

  if [[ "${OFFLINE}" -eq 1 && "${SERVERS_SET}" -eq 0 && -z "${LOCAL_STRATUM}" ]]; then
    die "无外网模式必须指定 --servers（内网 NTP），或使用 --as-server --local-stratum"
  fi

  if [[ "${OFFLINE}" -eq 1 && "${SERVERS_SET}" -eq 0 ]]; then
    NTP_SERVERS=()
  fi

  if [[ "${AS_SERVER}" -eq 1 && ${#ALLOW_NETS[@]} -eq 0 ]]; then
    die "--as-server 必须指定 --allow \"网段...\"，例如 --allow \"10.0.0.0/8\""
  fi

  if [[ ${#NTP_SERVERS[@]} -eq 0 && -z "${LOCAL_STRATUM}" ]]; then
    die "至少需要一个 NTP 服务器，或使用 --local-stratum"
  fi
}

install_chrony() {
  if command -v chronyd >/dev/null 2>&1; then
    log "chrony 已安装"
    return
  fi

  log "安装 chrony..."
  if command -v dnf >/dev/null 2>&1; then
    if ! dnf install -y chrony; then
      die "安装 chrony 失败。无外网时请先配置本地 yum/dnf 源，或离线安装 chrony RPM"
    fi
  elif command -v yum >/dev/null 2>&1; then
    if ! yum install -y chrony; then
      die "安装 chrony 失败。无外网时请先配置本地 yum 源，或离线安装 chrony RPM"
    fi
  else
    die "未找到 dnf/yum，无法安装 chrony"
  fi
}

backup_conf() {
  if [[ -f "${CHRONY_CONF}" ]]; then
    cp -a "${CHRONY_CONF}" "${CHRONY_CONF}.bak.${BACKUP_SUFFIX}"
    log "已备份配置: ${CHRONY_CONF}.bak.${BACKUP_SUFFIX}"
  fi
}

configure_chrony() {
  log "写入 chrony 配置: ${CHRONY_CONF}"
  backup_conf

  local server_lines=""
  local allow_lines=""
  local local_lines=""
  local s

  for s in "${NTP_SERVERS[@]}"; do
    server_lines+="server ${s} iburst"$'\n'
  done

  if [[ "${AS_SERVER}" -eq 1 ]]; then
    for s in "${ALLOW_NETS[@]}"; do
      allow_lines+="allow ${s}"$'\n'
    done
  fi

  if [[ -n "${LOCAL_STRATUM}" ]]; then
    local_lines+="local stratum ${LOCAL_STRATUM}"$'\n'
  fi

  cat > "${CHRONY_CONF}" <<EOF
# Generated by rhel8-setup-chrony.sh on $(date -Iseconds)
# Mode: offline=${OFFLINE} as_server=${AS_SERVER}

# Upstream NTP servers (empty when using local clock only)
${server_lines}
# Serve time to LAN clients (only when --as-server)
${allow_lines}
# Local reference clock fallback (only when --local-stratum)
${local_lines}
# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
rtcsync

# Specify directory for log files.
logdir /var/log/chrony
EOF

  if [[ "${OFFLINE}" -eq 1 ]]; then
    log "已启用无外网模式，仅使用内网/本地时间源"
  fi
  if [[ "${AS_SERVER}" -eq 1 ]]; then
    log "已配置为本机 NTP 服务端，允许网段: ${ALLOW_NETS[*]}"
  fi
}

set_timezone_and_ntp() {
  if ! timedatectl list-timezones | grep -Fxq "${TIMEZONE}"; then
    die "无效时区: ${TIMEZONE}"
  fi
  log "设置时区为 ${TIMEZONE}"
  timedatectl set-timezone "${TIMEZONE}"

  log "启用 NTP 同步"
  timedatectl set-ntp true
}

open_firewall_if_server() {
  if [[ "${AS_SERVER}" -ne 1 ]]; then
    return
  fi
  if ! command -v firewall-cmd >/dev/null 2>&1; then
    warn "未检测到 firewall-cmd，请手动放行 UDP 123（NTP）"
    return
  fi
  if ! systemctl is-active --quiet firewalld; then
    warn "firewalld 未运行，跳过放行 NTP；如启用防火墙请手动放行 UDP 123"
    return
  fi
  log "放行 firewalld NTP 服务（UDP 123）"
  firewall-cmd --permanent --add-service=ntp >/dev/null
  firewall-cmd --reload >/dev/null
}

enable_service() {
  log "启用并启动 chronyd"
  systemctl enable --now chronyd
  systemctl restart chronyd
}

show_status() {
  echo
  log "==== timedatectl 状态 ===="
  timedatectl status || true
  echo
  log "==== chronyc tracking ===="
  chronyc tracking || true
  echo
  log "==== chronyc sources -v ===="
  chronyc sources -v || true
  if [[ "${AS_SERVER}" -eq 1 ]]; then
    echo
    log "==== chronyc clients ===="
    chronyc clients || true
  fi
  echo
  if [[ ${#NTP_SERVERS[@]} -gt 0 ]]; then
    log "配置完成。若 sources 暂无 *（当前同步源），请检查到 NTP 主机 UDP/123 连通性后重试: chronyc sources -v"
  else
    log "配置完成。当前使用本地时钟（local stratum），适合隔离内网作为时间源"
  fi
}

main() {
  parse_args "$@"
  require_root
  detect_os
  install_chrony
  configure_chrony
  set_timezone_and_ntp
  open_firewall_if_server
  enable_service
  show_status
}

main "$@"
